# Page settings

baseurl = "http://example.org/"
languageCode = "en-us"
title = "Dickson Armijos Resume"
theme = "hugo-orbit-theme"
googleAnalytics = "UA-XXXXXXX-Y"

# Do not build files for websites. Need them? Set to false
disableRSS = true
disableSitemap = true
disable404 = true

[params]

# Meta
description = "Hugo Responsive Resume/CV Theme for Developers"
author = "Pavel Kanyshev"

# Theme styles

# The original template comes with 6 colour schemes. You may choose styles below.
# "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
# are available. Also the source LESS files are included so
# it’s quick and easy to change the styling and colour scheme.

styles = "styles.css"

# Sidebar sections

# Profile section
[params.profile]
name = "Dickson Armijos R."
tagline = "Full Stack Developer"
avatar = "profile.jpeg"

# Contact section
[params.contact]
enable = true

[[params.contact.list]]
class = "email"
icon = "fa-envelope"
url = "mailto: fabidick22@hotmail.es"
title = "fabidick22@hotmail.es"

[[params.contact.list]]
class = "linkedin"
icon = "fa-linkedin"
url = "//linkedin.com/in/fabidick22"
title = "Dickson A."

[[params.contact.list]]
class = "github"
icon = "fa-github"
url = "//github.com/fabidick22"
title = "fabidick22"

[[params.contact.list]]
class = "twitter"
icon = "fa-twitter"
url = "//twitter.com/fabidick"
title = "@fabidick"
